import React from 'react';
import { StructuredSopDocument } from '../data/sopParser';
import { MathFormulaRenderer } from './MathFormulaRenderer';
import { FileText, Printer, RotateCcw } from 'lucide-react';

interface SopDocumentViewProps { sop: StructuredSopDocument; onOpenHtmlModal?: () => void; onOpenStudio?: () => void; }
const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => <section className="mb-6"><div className="flex items-center gap-2 border-b border-slate-400 pb-1 mb-2"><h2 className="text-sm font-bold uppercase tracking-wider text-slate-900">{title}</h2></div>{children}</section>;

export const SopDocumentView: React.FC<SopDocumentViewProps> = ({ sop, onOpenHtmlModal, onOpenStudio }) => {
  const hasContent = Boolean(sop.documentTitle || sop.companyName || sop.purpose || sop.scope || sop.definitions.length || sop.safetyPrecautions.length || sop.apparatus.length || sop.reagents || sop.sampleHandling || sop.procedureStages.length || sop.calculations.length || sop.qualityControl || sop.references.length || sop.signatories.length || sop.revisionHistory.length);
  return <div className="space-y-5 max-w-5xl mx-auto pb-12">
    <div className="no-print bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex flex-wrap items-center justify-between gap-3">
      <div className="flex items-center gap-3"><FileText className="w-4 h-4" /><div><h2 className="text-sm font-bold truncate">{sop.documentTitle || 'Untitled SOP'}</h2><p className="text-xs text-slate-500">{sop.documentNumber || 'No document number'}{sop.revisionNumber ? ' · Rev ' + sop.revisionNumber : ''}</p></div></div>
      <div className="flex items-center gap-2">{onOpenStudio && <button onClick={onOpenStudio} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-slate-100 rounded-lg"><RotateCcw className="w-3.5 h-3.5" /> Edit Source</button>}{onOpenHtmlModal && <button onClick={onOpenHtmlModal} className="px-3 py-1.5 text-xs font-semibold bg-slate-100 rounded-lg">HTML</button>}<button onClick={() => window.print()} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-white bg-slate-900 rounded-lg"><Printer className="w-3.5 h-3.5" /> Print / PDF</button></div>
    </div>
    <article className="sop-page bg-white p-8 sm:p-10 shadow-lg border border-slate-300 rounded-sm">
      <header className="mb-6"><table className="w-full border-collapse border-2 border-slate-900 text-[11px]"><tbody><tr><td className="p-2 border border-slate-700 w-1/4"><div className="font-bold">SOP</div><div className="text-[9px] text-slate-500">Document</div></td><td className="p-2 border border-slate-700">{sop.companyName && <div className="font-bold uppercase">{sop.companyName}</div>}{sop.companySubtitle && <div className="text-slate-500">{sop.companySubtitle}</div>}{sop.companyAddress && <div className="text-slate-500">{sop.companyAddress}</div>}</td><td className="p-2 border border-slate-700 w-1/3">{sop.documentNumber && <div><strong>Document:</strong> {sop.documentNumber}</div>}{sop.revisionNumber && <div><strong>Revision:</strong> {sop.revisionNumber}</div>}{sop.effectiveDate && <div><strong>Effective:</strong> {sop.effectiveDate}</div>}{sop.reviewDate && <div><strong>Review:</strong> {sop.reviewDate}</div>}</td></tr><tr><td colSpan={3} className="p-3 text-center border border-slate-700 bg-slate-50"><div className="text-[10px] uppercase tracking-wider text-slate-500">Standard Operating Procedure</div><div className="text-lg font-bold uppercase mt-1">{sop.documentTitle || 'Untitled SOP'}</div>{sop.department && <div className="text-[10px] text-slate-500 mt-1">{sop.department}</div>}{sop.isoStandard && <div className="text-[10px] text-slate-500 mt-1">{sop.isoStandard}</div>}</td></tr></tbody></table></header>
      {sop.purpose && <Section title="Purpose"><p className="text-xs leading-relaxed whitespace-pre-wrap">{sop.purpose}</p></Section>}
      {sop.scope && <Section title="Scope"><p className="text-xs leading-relaxed whitespace-pre-wrap">{sop.scope}</p></Section>}
      {sop.definitions.length > 0 && <Section title="Definitions and Abbreviations"><div className="space-y-1.5 text-xs">{sop.definitions.map((x,i)=><p key={i}><strong>{x.term}:</strong> {x.definition}</p>)}</div></Section>}
      {sop.safetyPrecautions.length > 0 && <Section title="Safety"><ul className="list-disc ml-5 space-y-1 text-xs">{sop.safetyPrecautions.map((x,i)=><li key={i}><strong>{x.title}</strong>{x.desc ? ': '+x.desc : ''}</li>)}</ul></Section>}
      {sop.apparatus.length > 0 && <Section title="Equipment / Apparatus"><table className="w-full border-collapse border border-slate-300 text-xs"><thead><tr><th className="p-2 border border-slate-300 text-left">Item</th><th className="p-2 border border-slate-300 text-left">Specification</th><th className="p-2 border border-slate-300 text-left">Tolerance</th></tr></thead><tbody>{sop.apparatus.map((x,i)=><tr key={i}><td className="p-2 border border-slate-300">{x.name}</td><td className="p-2 border border-slate-300">{x.spec}</td><td className="p-2 border border-slate-300">{x.tolerance || ''}</td></tr>)}</tbody></table></Section>}
      {sop.reagents && <Section title="Reagents / Materials"><p className="text-xs leading-relaxed whitespace-pre-wrap">{sop.reagents}</p></Section>}
      {sop.sampleHandling && <Section title="Sample Handling / Preparation"><p className="text-xs leading-relaxed whitespace-pre-wrap">{sop.sampleHandling}</p></Section>}
      {sop.procedureStages.length > 0 && <Section title="Procedure">{sop.procedureStages.map((stage,i)=><div key={i} className="mb-4"><h3 className="text-xs font-bold bg-slate-100 border-l-4 border-slate-500 px-2 py-1 mb-2">{stage.stageName}</h3><ol className="ml-5 list-decimal space-y-1.5 text-xs">{stage.steps.map((step,j)=><li key={j}>{step.title ? <><strong>{step.title}:</strong> </> : null}{step.text}</li>)}</ol></div>)}</Section>}
      {sop.calculations.length > 0 && <Section title="Calculations / Formulas">{sop.calculations.map((calc,i)=><div key={i} className="border border-slate-300 rounded p-3 mb-3"><div className="font-bold text-xs mb-2">{calc.name}</div><MathFormulaRenderer formula={calc.formula}/>{calc.explanation && <p className="text-xs mt-2">{calc.explanation}</p>}{calc.variables?.length ? <ul className="text-[11px] mt-2">{calc.variables.map((v,j)=><li key={j}><strong>{v.symbol}:</strong> {v.description}{v.unit ? ' ('+v.unit+')' : ''}</li>)}</ul> : null}</div>)}</Section>}
      {sop.qualityControl && <Section title="Quality / Control Notes"><p className="text-xs leading-relaxed whitespace-pre-wrap">{sop.qualityControl}</p></Section>}
      {sop.references.length > 0 && <Section title="References"><ul className="list-disc ml-5 space-y-1 text-xs">{sop.references.map((x,i)=><li key={i}>{x}</li>)}</ul></Section>}
      {sop.revisionHistory.length > 0 && <Section title="Revision History"><table className="w-full border-collapse border border-slate-300 text-[11px]"><tbody>{sop.revisionHistory.map((x,i)=><tr key={i}><td className="p-2 border border-slate-300">{x.rev}</td><td className="p-2 border border-slate-300">{x.date}</td><td className="p-2 border border-slate-300">{x.description}</td><td className="p-2 border border-slate-300">{x.preparedBy}</td><td className="p-2 border border-slate-300">{x.approvedBy}</td></tr>)}</tbody></table></Section>}
      {sop.signatories.length > 0 && <Section title="Document Signatories"><div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{sop.signatories.map((x,i)=><div key={i} className="border border-slate-300 p-3 text-center text-xs"><div className="font-bold uppercase text-[10px]">{x.role}</div><div className="mt-3 font-semibold">{x.name}</div><div>{x.designation}</div><div className="text-[10px] mt-1">{x.date}</div></div>)}</div></Section>}
      {!hasContent && <div className="py-16 text-center text-sm text-slate-400">No SOP content yet. Use Build / Import or Fields to begin.</div>}
    </article>
  </div>;
};
